set_property SRC_FILE_INFO {cfile:D:/APB/Constraints_basys3.xdc rfile:../../../../Constraints_basys3.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W5   IOSTANDARD LVCMOS33} [get_ports PCLK]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18   IOSTANDARD LVCMOS33} [get_ports PRESETn]
